import { useState } from 'react';
import { Check, Plus, Trash2 } from 'lucide-react';
import type { Expense, PaymentMethod, Reimbursement } from './types';
import { advanceRemaining, dateFr, id, money, reimbursedAmount } from './data';

const today = () => new Date().toISOString().slice(0, 10);
const methods: [PaymentMethod, string][] = [['bank', 'Virement bancaire'], ['cash', 'Cash'], ['other', 'Autre']];
const methodLabel = (method: PaymentMethod) => methods.find(([key]) => key === method)?.[1] || 'Autre';

export function AdvancesPage({ expenses, onSave, onDelete, onNewExpense }: {
  expenses: Expense[];
  onSave: (expenseId: string, value: Reimbursement) => string | void;
  onDelete: (expenseId: string, reimbursementId: string) => void;
  onNewExpense: () => void;
}) {
  const advances = expenses.filter(item => item.paid && item.fundingSource === 'personal').sort((a, b) => b.date.localeCompare(a.date));
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [draft, setDraft] = useState<Reimbursement | null>(null);
  const [error, setError] = useState('');
  const selected = advances.find(item => item.id === selectedId);
  const total = advances.reduce((sum, item) => sum + item.amount, 0);
  const refunded = advances.reduce((sum, item) => sum + reimbursedAmount(item), 0);
  const outstanding = advances.reduce((sum, item) => sum + advanceRemaining(item), 0);
  const startRefund = (expense: Expense, value?: Reimbursement) => { setSelectedId(expense.id); setDraft(value ? { ...value } : { id: id(), date: today(), amount: advanceRemaining(expense), method: 'bank', note: '' }); setError(''); };
  const save = (event: React.FormEvent) => { event.preventDefault(); if (!selected || !draft) return; const issue = onSave(selected.id, draft); if (issue) setError(issue); else { setDraft(null); setError(''); } };
  return <>
    <div className="page-title-row"><div><div className="eyebrow">Avances personnelles</div><h1>Finances à ajouter</h1><p>Suivez les dépenses de la société payées avec votre argent, puis leurs remboursements. Chaque dépense reste enregistrée une seule fois.</p></div><button className="button primary" onClick={onNewExpense}><Plus size={17}/> Saisir une dépense</button></div>
    <div className="finance-summary advance-summary"><div><span>Total avancé</span><strong>{money(total)}</strong></div><div><span>Déjà remboursé</span><strong>{money(refunded)}</strong></div><div><span>Reste à me rembourser</span><strong>{money(outstanding)}</strong></div></div>
    <div className="panel list-panel"><div className="panel-heading"><h3>Avances liées aux dépenses</h3><small>{advances.length} dépense(s)</small></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Dépense</th><th>Payée avec</th><th>Montant avancé</th><th>Remboursé</th><th>Reste</th><th></th></tr></thead><tbody>{advances.map(item => <tr key={item.id} onClick={() => { setSelectedId(item.id); setDraft(null); }}><td>{dateFr(item.date)}</td><td><strong>{item.label}</strong>{item.person && <small>Pour {item.person}</small>}{item.month && <small>{item.month}</small>}</td><td>{item.paymentMethod === 'cash' ? 'Cash personnel' : item.paymentMethod === 'bank' ? 'Banque personnelle' : 'Personnel'}</td><td className="amount">{money(item.amount)}</td><td className="amount">{money(reimbursedAmount(item))}</td><td className="amount"><strong>{money(advanceRemaining(item))}</strong></td><td><button className="button soft" onClick={event => { event.stopPropagation(); startRefund(item); }} disabled={advanceRemaining(item) <= 0}>Rembourser</button></td></tr>)}</tbody></table></div>{!advances.length && <div className="finance-empty">Aucune avance personnelle enregistrée. Dans « Sorties d’argent », choisissez « Mon argent personnel » et marquez la dépense comme payée.</div>}</div>
    {selected && <div className="modal-backdrop" onMouseDown={() => { setSelectedId(null); setDraft(null); }}><div className="modal form-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Remboursement interne</span><h2>{selected.label}</h2></div><button className="icon-button" onClick={() => { setSelectedId(null); setDraft(null); }}>✕</button></div><div className="advance-detail"><span>Avancé : <strong>{money(selected.amount)}</strong></span><span>Remboursé : <strong>{money(reimbursedAmount(selected))}</strong></span><span>Reste : <strong>{money(advanceRemaining(selected))}</strong></span></div><div className="finance-hint">Un remboursement est un transfert vers vous. Il ne crée ni une nouvelle dépense, ni une entrée client.</div>{!!selected.reimbursements.length && <div className="advance-history"><strong>Historique des remboursements</strong>{[...selected.reimbursements].sort((a, b) => b.date.localeCompare(a.date)).map(item => <div key={item.id}><span>{dateFr(item.date)} · {methodLabel(item.method)}<small>{item.note}</small></span><strong>{money(item.amount)}</strong><button className="icon-button" title="Modifier" onClick={() => startRefund(selected, item)}>Modifier</button><button className="icon-button" title="Supprimer" aria-label="Supprimer le remboursement" onClick={() => onDelete(selected.id, item.id)}><Trash2 size={16}/></button></div>)}</div>}{draft ? <form onSubmit={save}><div className="form-grid"><label>Date *<input type="date" value={draft.date} onChange={e => setDraft({ ...draft, date: e.target.value })} required/></label><label>Montant (DH) *<input type="number" min="0.01" step="0.01" value={draft.amount || ''} onChange={e => setDraft({ ...draft, amount: Number(e.target.value) })} required/></label><label>Mode de remboursement<select value={draft.method} onChange={e => setDraft({ ...draft, method: e.target.value as PaymentMethod })}>{methods.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Note<input value={draft.note} onChange={e => setDraft({ ...draft, note: e.target.value })}/></label></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={() => { setDraft(null); setError(''); }}>Annuler</button><button className="button primary" type="submit"><Check size={17}/> Enregistrer</button></div></form> : <div className="modal-actions"><button className="button ghost" onClick={() => setSelectedId(null)}>Fermer</button>{advanceRemaining(selected) > 0 && <button className="button primary" onClick={() => startRefund(selected)}><Plus size={17}/> Ajouter un remboursement</button>}</div>}</div></div>}
  </>;
}
