import { useState } from 'react';
import { Check, Plus, Trash2 } from 'lucide-react';
import type { CashEntry, Client, Document, Expense, ExpenseCategory, PaymentMethod, RecurringExpense } from './types';
import { dateFr, id, money, remaining } from './data';

const today = () => new Date().toISOString().slice(0, 10);
const monthNow = () => today().slice(0, 7);
const categories: [ExpenseCategory, string][] = [['electricity', 'Électricité'], ['water', 'Eau'], ['internet', 'Wi-Fi / Internet'], ['cloud', 'Cloud'], ['subscription', 'Autre abonnement'], ['office', 'Bureau / achat'], ['bonus', 'Prime'], ['other', 'Autre']];
const categoryLabel = (value: ExpenseCategory) => categories.find(([key]) => key === value)?.[1] || 'Autre';
const methods: [PaymentMethod, string][] = [['cash', 'Cash'], ['bank', 'Banque'], ['other', 'Autre']];
const methodLabel = (value: PaymentMethod) => methods.find(([key]) => key === value)?.[1] || 'Autre';
const emptyCash = (): CashEntry => ({ id: id(), date: today(), amount: 0, service: '', clientId: '', invoiceId: '', note: '' });
const emptyExpense = (): Expense => ({ id: id(), date: today(), label: '', amount: 0, category: 'office', paymentMethod: 'cash', person: '', note: '', paid: true, recurrenceId: '', month: '' });
const emptyRule = (): RecurringExpense => ({ id: id(), label: '', amount: 0, category: 'electricity', paymentMethod: 'bank', person: '', note: '', startMonth: monthNow(), endMonth: '' });

export function CashPage({ entries, clients, invoices, onSave, onDelete }: { entries: CashEntry[]; clients: Client[]; invoices: Document[]; onSave: (value: CashEntry) => string | void; onDelete: (value: CashEntry) => void }) {
  const [draft, setDraft] = useState<CashEntry | null>(null);
  const [error, setError] = useState('');
  const [filterMonth, setFilterMonth] = useState(monthNow());
  const shown = [...entries].filter(item => !filterMonth || item.date.startsWith(filterMonth)).sort((a, b) => b.date.localeCompare(a.date));
  const update = <K extends keyof CashEntry>(key: K, value: CashEntry[K]) => setDraft(current => current ? { ...current, [key]: value } : current);
  const save = (event: React.FormEvent) => { event.preventDefault(); if (!draft) return; const issue = onSave(draft); if (issue) setError(issue); else { setDraft(null); setError(''); } };
  return <>
    <div className="page-title-row"><div><div className="eyebrow">Encaissements</div><h1>Paiements en cash</h1><p>Notez le montant et la prestation. Le rattachement à une facture reste facultatif.</p></div><button className="button primary" onClick={() => { setDraft(emptyCash()); setError(''); }}><Plus size={18}/> Nouveau paiement</button></div>
    <div className="finance-summary"><div><span>Entrées cash · {filterMonth || 'toutes périodes'}</span><strong>{money(shown.reduce((sum, item) => sum + item.amount, 0))}</strong></div><label>Mois affiché<input type="month" value={filterMonth} onChange={e => setFilterMonth(e.target.value)}/></label><button className="button ghost" onClick={() => setFilterMonth('')}>Tout voir</button></div>
    <div className="panel list-panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Service</th><th>Client / facture</th><th>Montant</th><th></th></tr></thead><tbody>{shown.map(item => { const client = clients.find(c => c.id === item.clientId); const invoice = invoices.find(d => d.id === item.invoiceId); return <tr key={item.id} onClick={() => { setDraft({ ...item }); setError(''); }}><td>{dateFr(item.date)}</td><td><strong>{item.service}</strong>{item.note && <small>{item.note}</small>}</td><td>{client?.name || 'Sans client'}{invoice && <small>{invoice.reference || 'Brouillon'}</small>}</td><td className="amount">{money(item.amount)}</td><td><button className="icon-button" title="Supprimer" aria-label="Supprimer" onClick={e => { e.stopPropagation(); onDelete(item); }}><Trash2 size={16}/></button></td></tr>; })}</tbody></table></div>{!shown.length && <div className="finance-empty">Aucun paiement cash pour cette période.</div>}</div>
    {draft && <div className="modal-backdrop" onMouseDown={() => setDraft(null)}><div className="modal form-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Entrée d’argent</span><h2>{entries.some(item => item.id === draft.id) ? 'Modifier le paiement' : 'Nouveau paiement cash'}</h2></div><button className="icon-button" onClick={() => setDraft(null)}>✕</button></div><form onSubmit={save}><div className="form-grid"><label>Date *<input type="date" value={draft.date} onChange={e => update('date', e.target.value)} required/></label><label>Montant (DH) *<input type="number" min="0.01" step="0.01" value={draft.amount || ''} onChange={e => update('amount', Number(e.target.value))} required/></label><label className="wide">Service réalisé *<input value={draft.service} onChange={e => update('service', e.target.value)} required placeholder="Ex. création de contenu"/></label><label>Client (facultatif)<select value={draft.clientId} onChange={e => setDraft({ ...draft, clientId: e.target.value, invoiceId: '' })}><option value="">Sans client</option>{clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Facture à régler (facultatif)<select value={draft.invoiceId} onChange={e => update('invoiceId', e.target.value)} disabled={!draft.clientId}><option value="">Sans facture</option>{invoices.filter(d => d.clientId === draft.clientId && (remaining(d) > 0 || d.id === draft.invoiceId) && d.historicalPaymentStatus !== 'paid').map(d => <option key={d.id} value={d.id}>{d.reference || 'Brouillon'} · reste {money(remaining(d))}</option>)}</select></label><label className="wide">Note<input value={draft.note} onChange={e => update('note', e.target.value)}/></label></div>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="button ghost" onClick={() => setDraft(null)}>Annuler</button><button className="button primary" type="submit"><Check size={17}/> Enregistrer</button></div></form></div></div>}
  </>;
}

export function ExpensesPage({ expenses, rules, onSaveExpense, onDeleteExpense, onSaveRule, onStopRule }: { expenses: Expense[]; rules: RecurringExpense[]; onSaveExpense: (value: Expense) => void; onDeleteExpense: (value: Expense) => void; onSaveRule: (value: RecurringExpense) => void; onStopRule: (value: RecurringExpense) => void }) {
  const [draft, setDraft] = useState<Expense | null>(null);
  const [ruleDraft, setRuleDraft] = useState<RecurringExpense | null>(null);
  const [filterMonth, setFilterMonth] = useState(monthNow());
  const shown = [...expenses].filter(item => !filterMonth || item.date.startsWith(filterMonth) || item.month === filterMonth).sort((a, b) => b.date.localeCompare(a.date));
  const paid = shown.filter(item => item.paid);
  const bonuses = paid.filter(item => item.category === 'bonus');
  const bonusByPerson = Object.entries(bonuses.reduce<Record<string, number>>((acc, item) => { acc[item.person] = (acc[item.person] || 0) + item.amount; return acc; }, {}));
  const update = <K extends keyof Expense>(key: K, value: Expense[K]) => setDraft(current => current ? { ...current, [key]: value } : current);
  const updateRule = <K extends keyof RecurringExpense>(key: K, value: RecurringExpense[K]) => setRuleDraft(current => current ? { ...current, [key]: value } : current);
  const saveExpense = (event: React.FormEvent) => { event.preventDefault(); if (!draft?.label.trim() || draft.amount <= 0 || (draft.category === 'bonus' && !draft.person.trim())) return; onSaveExpense(draft); setDraft(null); };
  const saveRule = (event: React.FormEvent) => { event.preventDefault(); if (!ruleDraft?.label.trim() || ruleDraft.amount <= 0 || (ruleDraft.category === 'bonus' && !ruleDraft.person.trim())) return; onSaveRule(ruleDraft); setRuleDraft(null); };
  return <>
    <div className="page-title-row"><div><div className="eyebrow">Suivi interne</div><h1>Sorties d’argent</h1><p>Dépenses ponctuelles, primes et charges mensuelles. Chaque échéance peut être marquée comme payée.</p></div><div className="finance-actions"><button className="button outline" onClick={() => setRuleDraft(emptyRule())}><Plus size={17}/> Charge mensuelle</button><button className="button primary" onClick={() => setDraft(emptyExpense())}><Plus size={17}/> Dépense / prime</button></div></div>
    <div className="finance-summary"><div><span>Sorties payées · {filterMonth || 'toutes périodes'}</span><strong>{money(paid.reduce((sum, item) => sum + item.amount, 0))}</strong></div><div><span>Primes payées</span><strong>{money(bonuses.reduce((sum, item) => sum + item.amount, 0))}</strong></div><label>Mois affiché<input type="month" value={filterMonth} onChange={e => setFilterMonth(e.target.value)}/></label><button className="button ghost" onClick={() => setFilterMonth('')}>Tout voir</button></div>
    {!!bonusByPerson.length && <div className="finance-bonuses"><strong>Primes par personne</strong>{bonusByPerson.map(([name, amount]) => <span key={name}>{name} · {money(amount)}</span>)}</div>}
    <div className="panel list-panel"><div className="panel-heading"><h3>Registre des sorties</h3><small>{shown.length} ligne(s)</small></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Dépense</th><th>Type</th><th>Paiement</th><th>Montant</th><th>État</th><th></th></tr></thead><tbody>{shown.map(item => <tr key={item.id} onClick={() => setDraft({ ...item })}><td>{dateFr(item.date)}</td><td><strong>{item.label}</strong>{item.person && <small>Pour {item.person}</small>}{item.recurrenceId && <small>Mensuelle · {item.month}</small>}</td><td>{categoryLabel(item.category)}</td><td>{methodLabel(item.paymentMethod)}</td><td className="amount">{money(item.amount)}</td><td><span className={`status ${item.paid ? 'payée' : 'en-attente'}`}>{item.paid ? 'Payée' : 'Prévue'}</span></td><td>{!item.recurrenceId && <button className="icon-button" title="Supprimer" aria-label="Supprimer" onClick={e => { e.stopPropagation(); onDeleteExpense(item); }}><Trash2 size={16}/></button>}</td></tr>)}</tbody></table></div>{!shown.length && <div className="finance-empty">Aucune sortie pour cette période.</div>}</div>
    <div className="panel finance-rules"><div className="panel-heading"><h3>Charges mensuelles</h3><small>Générées du mois de départ jusqu’à l’arrêt</small></div>{rules.length ? rules.map(rule => <div className="finance-rule" key={rule.id}><div><strong>{rule.label}</strong><small>{categoryLabel(rule.category)} · {money(rule.amount)} / mois · depuis {rule.startMonth}{rule.endMonth ? ` · arrêtée ${rule.endMonth}` : ''}</small></div><button className="button outline" onClick={() => setRuleDraft({ ...rule })}>Modifier</button>{!rule.endMonth && <button className="button danger-text" onClick={() => onStopRule(rule)}>Arrêter</button>}</div>) : <div className="finance-empty">Aucune charge mensuelle configurée.</div>}</div>
    {draft && <div className="modal-backdrop" onMouseDown={() => setDraft(null)}><div className="modal form-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Sortie d’argent</span><h2>{draft.recurrenceId ? 'Échéance mensuelle' : 'Dépense / prime'}</h2></div><button className="icon-button" onClick={() => setDraft(null)}>✕</button></div><form onSubmit={saveExpense}><div className="form-grid"><label>Date *<input type="date" value={draft.date} onChange={e => update('date', e.target.value)} required/></label><label>Montant (DH) *<input type="number" min="0.01" step="0.01" value={draft.amount || ''} onChange={e => update('amount', Number(e.target.value))} required/></label><label className="wide">Libellé *<input value={draft.label} onChange={e => update('label', e.target.value)} required placeholder="Ex. abonnement cloud"/></label><label>Catégorie<select value={draft.category} onChange={e => { const category = e.target.value as ExpenseCategory; setDraft({ ...draft, category, paymentMethod: category === 'bonus' ? 'cash' : draft.paymentMethod }); }}>{categories.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Mode de paiement<select value={draft.paymentMethod} onChange={e => update('paymentMethod', e.target.value as PaymentMethod)}>{methods.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{draft.category === 'bonus' && <label className="wide">Personne concernée *<input value={draft.person} onChange={e => update('person', e.target.value)} required/></label>}<label className="wide">Note<input value={draft.note} onChange={e => update('note', e.target.value)}/></label><label className="check-row wide"><input type="checkbox" checked={draft.paid} onChange={e => update('paid', e.target.checked)}/> Déjà payée</label></div><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setDraft(null)}>Annuler</button><button className="button primary" type="submit"><Check size={17}/> Enregistrer</button></div></form></div></div>}
    {ruleDraft && <div className="modal-backdrop" onMouseDown={() => setRuleDraft(null)}><div className="modal form-modal" onMouseDown={e => e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">Récurrence</span><h2>Charge mensuelle</h2></div><button className="icon-button" onClick={() => setRuleDraft(null)}>✕</button></div><form onSubmit={saveRule}><div className="form-grid"><label className="wide">Libellé *<input value={ruleDraft.label} onChange={e => updateRule('label', e.target.value)} required/></label><label>Montant prévu (DH) *<input type="number" min="0.01" step="0.01" value={ruleDraft.amount || ''} onChange={e => updateRule('amount', Number(e.target.value))} required/></label><label>Mois de départ *<input type="month" value={ruleDraft.startMonth} onChange={e => updateRule('startMonth', e.target.value)} required/></label><label>Catégorie<select value={ruleDraft.category} onChange={e => updateRule('category', e.target.value as ExpenseCategory)}>{categories.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Mode habituel<select value={ruleDraft.paymentMethod} onChange={e => updateRule('paymentMethod', e.target.value as PaymentMethod)}>{methods.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{ruleDraft.category === 'bonus' && <label className="wide">Personne concernée *<input value={ruleDraft.person} onChange={e => updateRule('person', e.target.value)} required/></label>}<label className="wide">Note<input value={ruleDraft.note} onChange={e => updateRule('note', e.target.value)}/></label></div><div className="finance-hint">Les mois déjà créés gardent leur montant. Le nouveau montant s’applique aux prochains mois.</div><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setRuleDraft(null)}>Annuler</button><button className="button primary" type="submit"><Check size={17}/> Enregistrer</button></div></form></div></div>}
  </>;
}
